import org.junit.Test;

import TextMessageReciver.Reciver;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'muszkie' at '5/10/17 10:54 AM' with Gradle 2.14.1
 *
 * @author muszkie, @date 5/10/17 10:54 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void senderTest() {
		Reciver reciver = new Reciver();
		reciver.recive();
		reciver.closeConnection();
		System.exit(0);
    }
}
